version: '3.7'
services:
  app:
    build: .
    volumes:
      - .:/app/speech_to_text
    environment:
      MP3_FILE_PATH: ${MP3_FILE_PATH}
      GOOGLE_APPLICATION_CREDENTIALS: '/app/speech_to_text/config/service_account.json'